version: 2

models:
  - name: dim_musteri
    description: "Raporlama için kullanılan nihai müşteri boyut tablosu."
    columns:
      - name: musteri_id
        description: "Müşterinin tekil kimlik numarası."
        tests:
          - unique
          - not_null

  - name: fct_islem
    description: "Müşterilerin temizlenmiş hesap hareketleri tablosu."
    columns:
      - name: islem_id
        tests:
          - unique
          - not_null
      - name: musteri_id
        tests:
          - relationships:
              to: ref('dim_musteri')
              field: musteri_id